### ISSUE TITLE
How to change RESET Pin?

### ISSUE THREAD

**Issue by nagibatorSPB** [mertenats/Open-Home-Automation#11]
Hello! Thank you for your work! Could you ask me, how to change D0 pin to other?
D0/GPIO16 - RST (wake-up purpose)
I cant find in sketch...

**Comment by mertenats** [comment]
Hi,
In which sketch?

**Comment by nagibatorSPB** [comment]
In ha_mqtt_sensor_dht22 :)

**Comment by mertenats** [comment]
You cannot change this pin, it's hardware. It's used to wake up the board after a period of time (D0: wake, to RST)
