### ISSUE TITLE
Can the brightness be increased from 255 to 1023? 

### ISSUE THREAD

**Issue by outnabout** [mertenats/Open-Home-Automation#13]
I have your sketch running to power some white led strips. When I plug them directly in the power source they are much brighter then when they run through the PWM of the NodeMCU. 

I found here that the brightness level should be adjusted from 255 to 1023 for the ESP8266. Read about it in his Update here:
https://eryk.io/2015/10/esp8266-based-wifi-rgb-controller-h801/

Can you tell me if that is possible with this Sketch. I tried but it does not work.

**Comment by mertenats** [comment]
Hi @outnabout,
Try to use this command ` analogWriteRange(255);` in your `setup()`function  to reduce the range to 0-255. 
Sam
