### ISSUE TITLE
Arduino ethernet

### ISSUE THREAD

**Issue by sobiso** [mertenats/Open-Home-Automation#15]
I new in arduino world. It's possible to change yours lib/programs from ESP8266 to Arduino with ethernet shield ? I'm very interested update the firmware over-the-air.

**Comment by mertenats** [comment]
Hi @sobiso,
I think that the OTA library isn't compatible with the Arduino boards or the internal memory is probably too limited. Why not buying ESP8266 boards? It's probably possible to add an Ethernet port to them and they cost less money.

Sam

**Comment by sobiso** [comment]
Good point with adding eth port to ESP8266. I prefer cable connection. It's possible to change Mqtt 'path' without re-programm ESP ?

**Comment by mertenats** [comment]
I'm not sure to understand your question. Normally, in all my sketches, the MQTT topics are hardcoded/derived from the device ID inside the source code. Feel free to modify them.

Sam

**Comment by sobiso** [comment]
I'm thinking about one universal program ex. switch. So you don't have to set each time new topic and re-program. This topic can be set via http or something like that and save to eeprom. What are you thinking about this ?

Kuba
