### ISSUE TITLE
Multiple lights on same board

### ISSUE THREAD

**Issue by 89merkur** [mertenats/Open-Home-Automation#16]
I wish to control multiple lights on the same board. Could someone give me an example of the edits for this sketch (mostly how to set topics for publish and subscribe). I am very new to mqtt and hassio so any help would be greatly appreciated.  I was able to get this example working for the single control and have tried to edit sketch for two lights.  Thanks in advance..

**Comment by mertenats** [comment]
Hi @89merkur,
Someone asked me the same question a few months ago. Just look at this [issue](https://github.com/mertenats/Open-Home-Automation/issues/1), a example is provided.

Sam
