### ISSUE TITLE
Add TEMT6000 Light Sensor support

### ISSUE THREAD

**Issue by pidiet** [mertenats/Open-Home-Automation#31]
Hello!

very nice sensor (less than a buck). Would be nice to see it working in the multisensor sketch =)

Link to product: https://www.aliexpress.com/item/Smart-Electronics-TEMT6000-An-ambient-light-sensor-Simulate-the-light-intensity-module-Visible-light-sensor/32583469115.html

**Comment by pidiet** [comment]
This project here makes use of the TEMT6000 sensor:
- https://github.com/bruhautomation/ESP-MQTT-JSON-Multisensor
maybe it's a good starting point?

**Comment by mertenats** [comment]
One sensor has just been ordered.

**Comment by mertenats** [comment]
The code is the same for a photoresistor or a TEMT6000 sensor. You just don't need to add a 10 kOhms resistor.
