### ISSUE TITLE
Support for inexpensive (US$ 0.5) radar sensor RCWL 0516

### ISSUE THREAD

**Issue by rradar** [mertenats/Open-Home-Automation#36]
Hello everybody!

Would be awesome if the radar sensor RCWL 0516 could be supported. It can detect human bodies in 360° within 5 meters. It can also sense thru thin walls, plastic, wood etc. It's a nice motion sensor but cheaper and more capable.

Looking forward to test it :+1:

**Comment by mertenats** [comment]
Hi @rradar,
One sensor has just been ordered.

**Comment by mertenats** [comment]
@rradar Support added in the last commit.

**Comment by rradar** [comment]
Wow! Thanks a lot! I will check it out (still waiting for my delivery...)
