### ISSUE TITLE
Great Job...You Made my new year

### ISSUE THREAD

**Issue by prasad7676** [mertenats/Open-Home-Automation#6]
Thank You Very Much for all your sources. I was looking this stuff all over internet but did not get this kind.

I need one help if you have time.

I'm using you sonoff.ino  where we can manage one relay is there way we can add few more relay? cause I'm using this for something else where I have 8ch relay so want to add that on it. with web configuration with mitt port, server, and topic for each 8relay?

**Comment by mertenats** [comment]
Hi,
Thank you for your message. Based on this work, samabsalom made probably an interesting sketch for you:  https://github.com/samabsalom/nodemcu-MQTT-8ch_relay-home_assistant
