### ISSUE TITLE
Great examples…one issue though

### ISSUE THREAD

**Issue by grahamwetzler** [mertenats/Open-Home-Automation#7]
I'm finding these examples very helpful. However, I did run into one issue that I believe I solved.

In the `setup() {}` function I believe you need to include `WiFi.mode(WIFI_STA)` to prevent the ESP from broadcasting an SSID. I believe this was causing my 2.4 GHz network from having poor performance.

For example:
```
void setup() {
...
WiFi.mode(WIFI_STA);
...
}
```

**Comment by mertenats** [comment]
Thank you. I corrected some of the examples.
