### ISSUE TITLE
Problem with brightness

### ISSUE THREAD

**Issue by matt123p** [mertenats/Open-Home-Automation#8]
I believe line 95 should read:

uint8_t brightness = map(m_rgb_brightness, 0, 100, 0, **255**);

i.e. the 1023 should be 255.  I correct this and it made the brightness function correctly.

Many thanks for a great project.

Matt.

**Comment by mertenats** [comment]
Thank you for your comment. Can you tell me the name of the sketch? I've made some corrections a few weeks ago about that.

I've normally reduce the resolution of the analog pin with (1023 by default):
`  analogWriteRange(255);`

And use this map function:
`  uint8_t brightness = map(m_rgb_brightness, 0, 100, 0, 255);`

EDIT: You're right, I forgot to modify the `ha_mqtt_rgb_light`sketch.
